# Generated by Django 3.0.4 on 2020-03-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='descr',
            field=models.TextField(default='Before Description', max_length=750),
        ),
    ]
