# Generated by Django 3.0.4 on 2020-03-23 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskline',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linetask', to='tasks.Task'),
        ),
    ]
